"""Shared configuration for RS485 motor control scripts."""

DEFAULT_OP_NO = 2

DEFAULT_SERIAL_PORT = "/dev/ttyUSB0"
DEFAULT_SERIAL_BAUDRATE = 9600
DEFAULT_MODBUS_TIMEOUT_SEC = 0.3

FIXED_PARITY = "E"
FIXED_STOPBITS = 1

DEFAULT_LEFT_SLAVE_ID = 2
DEFAULT_RIGHT_SLAVE_ID = 1

DEFAULT_LEFT_MOTOR_SIGN = -1
DEFAULT_RIGHT_MOTOR_SIGN = 1
